### ISSUE TITLE
 Create Chapter 7: Fetching Data

### ISSUE THREAD

**Issue by DevWeb13** [DevWeb13/learn-qwik#71]
![image](https://github.com/DevWeb13/learn-qwik/assets/81557059/23a5f7ee-cecd-40db-acf5-d13515eff604)

**Comment by DevWeb13** [comment]
- [ ] Add "https://www.learn-qwik.com/metaChapter7.png",

**Comment by zwl1619** [comment]
Looking forward to Chapter 7.

**Comment by DevWeb13** [comment]
> Looking forward to Chapter 7.

It won't be long...
